import { test, expect } from '@playwright/test';

test('工作记录按任务与时间折叠，操作合并且保留失败明细、展开和小窗口布局', async ({ page, request }) => {
  const state = await (await request.get('/api/state')).json();
  state.tasks = state.tasks.slice(0,2).map((task,i)=>({...task,id:i?'b':'a',title:i?'生成风景画':'整理迭代清单',status:'done'}));
  state.attentionIds=[]; state.managerBusy=false; state.preparation=null;
  const at=s=>`2026-09-07T10:${s}+08:00`;
  state.events=Array.from({length:40},(_,i)=>({id:`read-${i}`,taskId:'a',at:at(`00:${String(i).padStart(2,'0')}`),kind:'activity',tool:'read_file',status:'completed',text:'读取文件',path:`docs/file-${i}.md`,output:'文件内容已读取'}));
  state.events.push({id:'fail',taskId:'a',at:at('00:45'),kind:'activity',tool:'read_file',status:'failed',text:'读取文件',path:'missing.md',output:'文件不存在'}, {id:'a-end',taskId:'a',at:at('01:00'),kind:'delivery',text:'成果已准备好，等待验收'}, {id:'b-start',taskId:'b',at:at('03:00'),kind:'delivery',text:'风景画已生成'}, {id:'a-accept',taskId:'a',at:at('04:00'),kind:'accept',text:'成果已验收'});
  state.messages=[{id:'m',taskId:null,role:'user',text:'总结目前看板',at:at('02:00')},{id:'reply',taskId:null,role:'assistant',text:'目前有两项工作',at:at('02:10')}];
  await page.route('**/api/state',route=>route.fulfill({json:state}));
  await page.addInitScript(()=>{ window.EventSource=class {constructor(){window.historyStream=this;} close(){} }; });
  await page.goto('/');
  await page.waitForFunction(() => Boolean(window.historyStream?.onmessage));
  await page.evaluate(state=>window.historyStream.onmessage({data:JSON.stringify(state)}),state);
  await page.getByRole('button',{name:'工作记录',exact:true}).click();
  const groups=page.locator('.history-session');
  await expect(groups).toHaveCount(4);
  await expect(page.locator('.history-session[open]')).toHaveCount(0);
  await expect(groups.first().locator('summary').first()).toContainText('成果已验收');
  await expect(groups.nth(2).locator('summary').first()).toContainText('项目沟通');
  const older=page.locator('[data-history-id="read-0"]');
  await expect(older.locator('summary').first()).toContainText('42 条记录');
  await expect(older.locator('summary').first()).toContainText('1 条失败记录');
  await page.screenshot({path:'docs/screenshots/history-grouped.png'});
  await older.locator('summary').first().focus(); await page.keyboard.press('Enter');
  await expect(older).toHaveAttribute('open','');
  await expect(older.locator('.history-operations')).toHaveCount(1);
  await expect(older.locator('.history-operations > summary')).toContainText('读取 40 次');
  await older.locator('.history-record.failed summary').click();
  await expect(older.locator('.history-record.failed pre')).toContainText('missing.md\n文件不存在');
  state.events.push({id:'latest',taskId:'a',at:at('04:30'),kind:'priority',text:'优先级已更新'});
  await page.evaluate(state=>window.historyStream.onmessage({data:JSON.stringify(state)}),state);
  await expect(older).toHaveAttribute('open','');
  await expect(groups.first().locator('summary').first()).toContainText('优先级已更新');
  await older.locator('summary').first().click();
  await page.setViewportSize({width:390,height:844});
  const box=await page.locator('.work-history').boundingBox();
  expect(box.x).toBeGreaterThanOrEqual(0); expect(box.x+box.width).toBeLessThanOrEqual(390);
  await page.screenshot({path:'docs/screenshots/history-grouped-mobile.png'});
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
});
