import {test,expect} from '@playwright/test';
import {defaults} from '../../desktop/settings.mjs';
test('English settings apply immediately, keep drafts and user content, and survive reload',async({page,request})=>{
 const base=await(await request.get('/api/state')).json();const state={...base,tasks:[{...base.tasks[0],id:'language-task',title:'保留用户标题',goal:'保留用户目标',status:'paused',decision:null}],attentionIds:[],events:[],modelOptions:[],managerBusy:false,preparation:null};
 await page.route('**/api/state',r=>r.fulfill({json:state}));await page.addInitScript(({state,defaults})=>{
 window.EventSource=class{constructor(){queueMicrotask(()=>this.onmessage?.({data:JSON.stringify(state)}));}close(){}};
 window.desktop={getSettings:async()=>({...defaults,language:localStorage.getItem('workbench:language')||'zh',mode:'pi',projectPath:'/example/project',hasApiKey:true}),onCommand:()=>()=>{},savePreferences:async value=>window.savedLanguage=value.language,chatgptStatus:async()=>({loggedIn:false}),getModelProfiles:async()=>[],claudeStatus:async()=>({loggedIn:false})};
 },{state,defaults});
 await page.goto('/');await page.getByRole('textbox',{name:'交代工作或补充要求'}).fill('不要翻译这段草稿');await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'通用',exact:true}).click();await page.getByRole('combobox',{name:'语言',exact:true}).click();await page.getByRole('option',{name:'English',exact:true}).click();
 await expect(page.getByRole('navigation',{name:'Settings categories'})).toBeVisible();await expect(page.getByRole('combobox',{name:'Language',exact:true})).toHaveText('English');expect(await page.evaluate(()=>window.savedLanguage)).toBe('en');await expect(page.locator('html')).toHaveAttribute('lang','en-US');
 for(const name of ['Project','Project model','Permissions','Accounts & services','General']){await page.getByRole('navigation',{name:'Settings categories'}).getByRole('button',{name,exact:true}).click();const text=await page.locator('.settings-section').innerText();expect(text.replace('简体中文','')).not.toMatch(/\p{Script=Han}/u);}
 await page.getByRole('button',{name:'Close panel',exact:true}).click();await expect(page.locator('.focus-card h2')).toHaveText('保留用户标题');await expect(page.getByRole('textbox',{name:'Describe a task or add requirements'})).toHaveValue('不要翻译这段草稿');await expect(page.getByRole('button',{name:'Continue execution',exact:true})).toBeVisible();
 await page.reload();await expect(page.getByRole('heading',{name:'Workbench',exact:true})).toBeVisible();await expect(page.getByRole('textbox',{name:'Describe a task or add requirements'})).toHaveValue('不要翻译这段草稿');
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('navigation',{name:'Settings categories'}).getByRole('button',{name:'General',exact:true}).click();await page.screenshot({path:'docs/screenshots/language-settings-en.png'});
 await page.getByRole('combobox',{name:'Language',exact:true}).click();await page.getByRole('option',{name:'System',exact:true}).click();await page.evaluate(()=>{Object.defineProperty(navigator,'language',{value:'zh-CN',configurable:true});window.dispatchEvent(new Event('languagechange'));});await expect(page.getByRole('heading',{name:'设置',exact:true})).toBeVisible();await page.evaluate(()=>{Object.defineProperty(navigator,'language',{value:'en-US',configurable:true});window.dispatchEvent(new Event('languagechange'));});await expect(page.getByRole('heading',{name:'Settings',exact:true})).toBeVisible();
 await page.getByRole('combobox',{name:'Language',exact:true}).click();await page.getByRole('option',{name:'简体中文',exact:true}).click();await expect(page.getByRole('heading',{name:'设置',exact:true})).toBeVisible();
});
