import { test, expect } from '@playwright/test';

test('权限入口、任务联网审批和撤销沿用工作台，不改变草稿或提交对象', async ({ page, request }) => {
  const base = await (await request.get('/api/state')).json();
  const task = { ...base.tasks[0], id: 'permission-task', title: '检查项目', status: 'blocked', decision: { id: 'permission-one', kind: 'command', scope: 'network', question: '安装项目依赖', command: 'npm ci', recommendation: '允许命令联网；文件仍限制在项目与临时目录。任务授权持续到本次执行结束，可随时撤销。', options: ['允许本次执行', '本任务内允许联网', '拒绝并暂停'] } };
  let state = { ...base, project: { ...base.project, mode: 'pi' }, tasks: [task], attentionIds: [task.id], events: [], messages: [], permissions: { mode: 'auto', sandboxAvailable: true, grants: [] } };
  const actions = [], permissions = [];
  await page.route('**/api/state', route => route.fulfill({ json: state }));
  await page.addInitScript(state => { window.EventSource = class { constructor() { queueMicrotask(() => this.onmessage?.({ data: JSON.stringify(state) })); } close() {} }; }, state);
  await page.route('**/api/tasks/*/actions', async route => {
    actions.push(route.request().postDataJSON());
    state = { ...state, tasks: [{ ...task, status: 'running', decision: null }], attentionIds: [], permissions: { ...state.permissions, grants: [{ taskId: task.id, network: true }] } };
    await route.fulfill({ json: state });
  });
  await page.route('**/api/permissions', async route => {
    const change = route.request().postDataJSON(); permissions.push(change);
    state = { ...state, permissions: { ...state.permissions, mode: change.mode || state.permissions.mode, grants: [] } };
    await route.fulfill({ json: state });
  });
  await page.goto('/');
  const input = page.getByRole('textbox', { name: '交代工作或补充要求' });
  await input.fill('保留未发送的要求');
  await expect(page.locator('.outcome-label')).toHaveText('允许联网');
  await page.screenshot({ path: 'docs/screenshots/permission-approval.png' });
  await page.getByRole('button', { name: '本任务内允许联网', exact: true }).click();
  expect(actions).toEqual([{ type: 'decision', decisionId: 'permission-one', answer: '本任务内允许联网',expectedVersion:task.stateVersion,operationId:expect.any(String) }]);
  const chip = page.getByRole('button', { name: '权限模式：项目内自动', exact: true });
  await expect(page.locator('.composer')).toContainText('项目内自动');
  await chip.click();
  await expect(page.getByRole('radio', { name: '项目内自动' })).toBeChecked();
  await page.screenshot({ path: 'docs/screenshots/composer-permission-light.png' });
  await page.getByRole('button', { name: '管理授权 · 1' }).click();
  await expect(page.getByRole('region', { name: '命令权限' })).toBeVisible();
  await expect(page.locator('.permission-grant')).toContainText('检查项目');
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  expect(permissions[0]).toEqual({ revokeTaskId: task.id });
  await expect(page.getByText('暂无临时授权')).toBeVisible();
  await page.getByRole('combobox', { name: '审批模式', exact: true }).click();
  await page.getByRole('option', { name: '每条命令询问', exact: true }).click();
  expect(permissions[1]).toEqual({ mode: 'ask' });
  await page.setViewportSize({ width: 960, height: 720 });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.screenshot({ path: 'docs/screenshots/permission-settings.png' });
  await expect(page.getByRole('combobox', { name: '审批模式' })).toBeInViewport();
  await page.getByRole('button', { name: '关闭面板' }).click();
  await expect(input).toHaveValue('保留未发送的要求');
  const askChip = page.getByRole('button', { name: '权限模式：逐次询问', exact: true });
  await expect(askChip).toBeVisible();
  await askChip.click();
  await page.screenshot({ path: 'docs/screenshots/composer-permission-dark.png' });
  await page.getByRole('radio', { name: '项目内自动' }).click();
  await expect(chip).toBeVisible();
  expect(permissions[2]).toEqual({ mode: 'auto' });
  await expect(page.getByRole('dialog', { name: '权限模式', exact: true })).not.toBeVisible();
  await expect(input).toHaveValue('保留未发送的要求');
  await expect(page.getByRole('combobox', { name: '沟通范围' })).toHaveText('新任务');
  await chip.focus();
  await page.keyboard.press('Enter');
  await page.keyboard.press('Tab');
  await expect(page.getByRole('radio', { name: '项目内自动' })).toBeFocused();
  await page.keyboard.press('ArrowDown');
  await expect(askChip).toBeVisible();
  expect(permissions[3]).toEqual({ mode: 'ask' });
  await expect(askChip).toBeFocused();
  await page.setViewportSize({ width: 600, height: 720 });
  await askChip.click();
  await expect(page.getByRole('dialog', { name: '权限模式', exact: true })).toBeInViewport();
  await page.screenshot({ path: 'docs/screenshots/composer-permission-narrow.png' });
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog', { name: '权限模式', exact: true })).not.toBeVisible();
  await expect(input).toHaveValue('保留未发送的要求');
  expect(actions).toHaveLength(1);
});
