import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {_electron as electron} from 'playwright';
test('隐藏桌面 Claude 登录入口、官方未登录检查、授权码、取消及模型选择', {timeout:45000}, async t=>{
 const dir=await fs.mkdtemp('/tmp/boan-claude-desktop-');const env={...process.env,BOAN_BACKGROUND_TEST:'1',BOAN_USER_DATA:dir};delete env.ELECTRON_RUN_AS_NODE;
 const executablePath=process.env.BOAN_TEST_EXECUTABLE;const app=await electron.launch({...(executablePath?{executablePath,args:[]}:{args:[path.resolve('.')]}),env});t.after(async()=>{await app.close().catch(()=>{});await fs.rm(dir,{recursive:true,force:true});});const page=await app.firstWindow();await page.waitForSelector('.desktop-app');
 assert.equal((await page.evaluate(()=>window.desktop.claudeStatus())).loggedIn,false);
 await app.evaluate(({ipcMain})=>{let loggedIn=false,pending=false;const state=()=>({loggedIn,pending,email:loggedIn?'fixture@example.test':null,plan:'pro'});for(const name of ['status','login','cancel','code','logout','models'])ipcMain.removeHandler('desktop:claude-'+name);ipcMain.handle('desktop:claude-status',state);ipcMain.handle('desktop:claude-login',()=>{pending=true;return state();});ipcMain.handle('desktop:claude-cancel',()=>{pending=false;return state();});ipcMain.handle('desktop:claude-code',()=>{pending=false;loggedIn=true;return state();});ipcMain.handle('desktop:claude-logout',()=>{loggedIn=false;return state();});ipcMain.handle('desktop:claude-models',()=>[{id:'sonnet',name:'Sonnet'}]);});
 await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'真实项目',exact:false}).click();await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'项目模型'}).click();await page.getByRole('button',{name:'Claude 登录 使用 Claude 账号订阅',exact:true}).click();
 assert.equal(await page.getByLabel('API Key',{exact:true}).count(),0);await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'账号与服务'}).click();await page.getByRole('button',{name:'使用 Claude 登录',exact:true}).click();await page.getByRole('button',{name:'取消 Claude 登录'}).click();await page.getByRole('button',{name:'使用 Claude 登录',exact:true}).click();await page.getByText('浏览器显示了授权码',{exact:true}).click();await page.getByLabel('Claude 授权码',{exact:true}).fill('public-fixture-code');await page.getByRole('button',{name:'提交授权码',exact:true}).click();await page.getByRole('button',{name:'退出 Claude 登录',exact:true}).waitFor();
 await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'项目模型'}).click();
 await page.getByRole('combobox',{name:'Claude 模型',exact:true}).click();await page.getByRole('option',{name:'Sonnet',exact:true}).click();await page.screenshot({path:'docs/screenshots/claude-login.png'});
 assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().some(w=>w.isVisible()||w.isFocused())),false);
});
