import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { _electron as electron } from 'playwright';
import { defaults } from '../../desktop/settings.mjs';
import { modelService } from '../helpers/model-service.mjs';
const until=async fn=>{for(let i=0;i<400;i++){if(await fn())return;await new Promise(r=>setTimeout(r,40));}throw Error('DeepSeek desktop task timed out');};

test('隐藏桌面：DeepSeek 配置预填、任务选择、API 执行、重启恢复与会话密钥失效', {timeout:60000}, async t=>{
  const dir=await fs.mkdtemp('/tmp/boan-desktop-deepseek-'),project=path.join(dir,'project');await fs.mkdir(project);
  const {mock,requests}=modelService({strictDeepseek:true});await new Promise(r=>mock.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${mock.address().port}`;
  const env={...process.env,BOAN_BACKGROUND_TEST:'1',BOAN_USER_DATA:path.join(dir,'app-data')};delete env.ELECTRON_RUN_AS_NODE;
  const executablePath=process.env.BOAN_TEST_EXECUTABLE;
  const launch=()=>electron.launch({...(executablePath?{executablePath,args:[]}:{args:[path.resolve('.')]}),env});
  let app=await launch();t.after(async()=>{await app?.close().catch(()=>{});mock.closeAllConnections();await new Promise(r=>mock.close(r));await fs.rm(dir,{recursive:true,force:true});});
  let page=await app.firstWindow();await page.waitForSelector('.desktop-app');
  // A keyless local project stays available across restart; the added shared service uses a session key.
  await page.evaluate(c=>window.desktop.saveSettings(c),{...defaults,mode:'pi',connection:'api',provider:'deepseek',projectPath:project,baseUrl:url,model:'deepseek-v4-flash',keyStorage:'encrypted'});
  const state=()=>page.evaluate(()=>fetch('/api/state').then(r=>r.json()));
  await until(async()=>{try{return(await state()).project.mode==='pi';}catch{return false;}});
  await page.getByRole('button',{name:'设置',exact:true}).click();
  await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'账号与服务'}).click();
  await page.getByRole('button',{name:'添加厂商',exact:true}).click();
  await page.getByRole('combobox',{name:'厂商',exact:true}).click();await page.getByRole('option',{name:'DeepSeek',exact:true}).click();
  assert.equal(await page.getByLabel('服务名称',{exact:true}).inputValue(),'DeepSeek');
  assert.match(await page.getByRole('combobox',{name:'模型',exact:true}).innerText(),/deepseek-v4-flash.*deepseek-v4-pro/);
  assert.equal(await page.getByLabel('服务端点',{exact:true}).getAttribute('placeholder'),'留空使用 DeepSeek 官方地址');
  await page.getByRole('combobox',{name:'模型',exact:true}).click();
  await page.getByRole('textbox',{name:'搜索模型',exact:true}).fill('v4-pro');
  assert.equal(await page.getByRole('option').count(),1);
  await fs.mkdir('docs/screenshots',{recursive:true});await page.screenshot({path:'docs/screenshots/deepseek-model-search.png'});
  await page.getByRole('textbox',{name:'搜索模型',exact:true}).press('Escape');
  await page.getByLabel('服务端点',{exact:true}).fill(url);await page.getByLabel('服务 API Key',{exact:true}).fill('public-deepseek-desktop-fixture');
  await page.getByLabel('仅本次运行保存服务密钥',{exact:true}).check();
  await fs.mkdir('docs/screenshots',{recursive:true});await page.screenshot({path:'docs/screenshots/deepseek-service.png'});
  await page.getByRole('button',{name:'保存服务',exact:true}).click();await page.getByRole('group',{name:'配置模型服务'}).waitFor({state:'detached'});
  await page.getByRole('button',{name:'关闭面板'}).click();
  await page.getByRole('button',{name:'任务模型：deepseek-v4-flash',exact:true}).click();
  await page.getByRole('dialog',{name:'选择任务模型'}).getByRole('button',{name:/^deepseek-v4-pro/}).click();
  await page.getByRole('button',{name:'任务参数',exact:true}).click();
  await page.getByRole('combobox',{name:'思考强度（effort）'}).click();await page.getByRole('option',{name:'高',exact:true}).click();await page.keyboard.press('Escape');
  await page.getByRole('textbox',{name:'交代工作或补充要求'}).fill('写入 DeepSeek 测试成果');await page.getByRole('button',{name:'发送要求',exact:true}).click();
  await until(async()=>['review','failed'].includes((await state()).tasks[0]?.status));
  const result=await state();assert.equal(result.tasks[0].status,'review',result.tasks[0].summary);assert.equal(result.tasks[0].modelSelection.effort,'high');
  assert.ok(requests.length>5);assert.ok(requests.every(r=>r.auth==='Bearer public-deepseek-desktop-fixture'&&r.thinking.type==='enabled'&&r.effort==='high'));
  assert.ok(!JSON.stringify(result).includes('public-deepseek-desktop-fixture'));
  assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().some(w=>w.isVisible()||w.isFocused())),false);
  await app.close();app=await launch();page=await app.firstWindow();await page.waitForSelector('.desktop-app');
  await until(async()=>{try{return(await state()).tasks[0]?.status==='review';}catch{return false;}});
  assert.equal((await state()).tasks[0].modelSelection.model,'deepseek-v4-pro');
  const profile=(await page.evaluate(()=>window.desktop.getModelProfiles())).find(p=>p.name==='DeepSeek');assert.equal(profile.hasApiKey,false);
  assert.ok(!(await fs.readFile(path.join(dir,'app-data/model-profiles.json'),'utf8')).includes('public-deepseek-desktop-fixture'));
});
