import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { _electron as electron } from 'playwright';
import { defaults, projectId } from '../../desktop/settings.mjs';
import { modelService } from '../helpers/model-service.mjs';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const until=async fn=>{for(let i=0;i<400;i++){if(await fn())return;await delay(40);}throw Error('Desktop model task timed out');};
test('桌面配置第二厂商并逐任务切换：真实 SDK、私有凭据 IPC、输入框与原项目保持', {timeout:60000}, async t=>{
 const dir=await fs.mkdtemp('/tmp/boan-desktop-models-'),project=path.join(dir,'project');await fs.mkdir(project);
 const {mock,requests}=modelService();await new Promise(r=>mock.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${mock.address().port}`;
 const env={...process.env,BOAN_BACKGROUND_TEST:'1',BOAN_USER_DATA:path.join(dir,'app-data')};delete env.ELECTRON_RUN_AS_NODE;
 const executablePath=process.env.BOAN_TEST_EXECUTABLE;
 const app=await electron.launch({...(executablePath?{executablePath,args:[]}:{args:[path.resolve('.')]}),env});
 t.after(async()=>{await app.close().catch(()=>{});await new Promise(r=>mock.close(r));await fs.rm(dir,{recursive:true,force:true});});
 const page=await app.firstWindow();await page.waitForSelector('.desktop-app');
 await page.evaluate(c=>window.desktop.saveSettings(c),{...defaults,mode:'pi',connection:'api',provider:'openai',projectPath:project,baseUrl:url+'/v1',model:'gpt-5',keyStorage:'session',apiKey:'public-key-a'});
 const state=()=>page.evaluate(()=>fetch('/api/state').then(r=>r.json()));await until(async()=>{try{return(await state()).project.mode==='pi';}catch{return false;}});
 await page.getByRole('button',{name:'任务模型：gpt-5',exact:true}).waitFor();
 await page.getByRole('button',{name:'任务参数',exact:true}).click();
 await page.getByRole('combobox',{name:'思考强度（effort）'}).click();await page.getByRole('option',{name:'高',exact:true}).click();
 await page.getByRole('combobox',{name:'速度（speed）'}).click();await page.getByRole('option',{name:'快速 · 优先处理',exact:true}).click();
 await page.keyboard.press('Escape');
 await page.getByRole('textbox',{name:'交代工作或补充要求'}).fill('写入第一项任务');await page.getByRole('button',{name:'发送要求',exact:true}).click();
 await until(async()=>['review','failed'].includes((await state()).tasks[0]?.status));assert.equal((await state()).tasks[0].status,'review',(await state()).tasks[0].summary);
 const workerPid=await fs.readFile(path.join(dir,'app-data/workspaces',projectId(await fs.realpath(project)),'server.lock'),'utf8');
 await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'账号与服务'}).click();
 await page.getByRole('button',{name:'添加厂商',exact:true}).click();
 await page.getByLabel('服务名称',{exact:true}).fill('Anthropic 测试');await page.getByRole('combobox',{name:'厂商',exact:true}).click();await page.getByRole('option',{name:'Anthropic',exact:true}).click();
 await page.getByLabel('服务端点',{exact:true}).fill(url);await page.getByLabel('模型 ID',{exact:true}).fill('model-b');await page.getByLabel('服务 API Key',{exact:true}).fill('public-key-b');await page.getByLabel('仅本次运行保存服务密钥',{exact:true}).check();
 await page.getByRole('button',{name:'保存服务',exact:true}).click();await page.getByRole('group',{name:'配置模型服务'}).waitFor({state:'detached'});
 assert.equal(await fs.readFile(path.join(dir,'app-data/workspaces',projectId(await fs.realpath(project)),'server.lock'),'utf8'),workerPid);
 await page.evaluate(()=>window.desktop.savePreferences({notifications:true}));assert.equal(await fs.readFile(path.join(dir,'app-data/workspaces',projectId(await fs.realpath(project)),'server.lock'),'utf8'),workerPid);
 await page.screenshot({path:'docs/screenshots/desktop-model-services.png'});
 await page.getByRole('button',{name:'关闭面板'}).click();
 await page.getByRole('button',{name:'任务模型：gpt-5',exact:true}).click();await page.getByRole('dialog',{name:'选择任务模型'}).getByRole('button',{name:/^model-b/}).click();
 await page.getByRole('textbox',{name:'交代工作或补充要求'}).fill('写入第二项任务');await page.getByRole('button',{name:'发送要求',exact:true}).click();
 await until(async()=>['review','failed'].includes((await state()).tasks[1]?.status));const result=await state();assert.equal(result.tasks[1].status,'review',result.tasks[1].summary);
 assert.equal(result.tasks[0].modelSelection.model,'gpt-5');assert.equal(result.tasks[0].modelSelection.effort,'high');assert.equal(result.tasks[0].modelSelection.speed,'priority');assert.ok(requests.filter(r=>r.model==='gpt-5').every(r=>r.effort==='high'&&r.tier==='priority'));assert.equal(result.tasks[1].modelSelection.model,'model-b');assert.equal(result.project.path,await fs.realpath(project));
 assert.ok(requests.some(r=>r.model==='gpt-5'&&r.auth==='Bearer public-key-a'));assert.ok(requests.some(r=>r.model==='model-b'&&r.auth==='public-key-b'&&r.path.startsWith('/v1/messages')));
 assert.ok(!JSON.stringify(result).includes('public-key-'));const publicProfiles=await page.evaluate(()=>window.desktop.getModelProfiles());assert.ok(!JSON.stringify(publicProfiles).includes('public-key-'));
 const raw=await fs.readFile(path.join(dir,'app-data/model-profiles.json'),'utf8');assert.ok(!raw.includes('public-key-'));
 assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().some(w=>w.isVisible()||w.isFocused())),false);
});
